#!/usr/bin/env bash
set -euo pipefail

ENV_FILE="${1:-/etc/alpaca_bot/alpaca-bot.env}"
MODE="${2:-paper}"
OPERATOR_USERNAME="${3:-operator@example.com}"

if [[ "$MODE" != "paper" && "$MODE" != "live" ]]; then
  echo "usage: $0 [env-file] [paper|live] [dashboard-username]" >&2
  exit 1
fi

mkdir -p "$(dirname "$ENV_FILE")"
mkdir -p /var/lib/alpaca-bot/nightly

if [[ -f "$ENV_FILE" ]]; then
  echo "env file already exists: $ENV_FILE" >&2
  exit 1
fi

POSTGRES_PASSWORD="$(python3 - <<'PY'
import secrets
print(secrets.token_urlsafe(24))
PY
)"

if [[ "$MODE" == "paper" ]]; then
  ENABLE_LIVE_TRADING="false"
  PAPER_PROOF_FREEZE="true"
  RISK_PER_TRADE_PCT="0.01"
  MAX_LOSS_PER_TRADE_DOLLARS="20.0"
  MAX_OPEN_POSITIONS="4"
  MAX_PORTFOLIO_EXPOSURE_PCT="0.30"
  REPLAY_SLIPPAGE_BPS="2.0"
  ENABLE_VIX_FILTER="false"
  ENABLE_SECTOR_FILTER="false"
  ENABLE_VWAP_ENTRY_FILTER="false"
  ENABLE_PROFIT_TRAIL="true"
  ENABLE_PROFIT_TARGET="true"
  PROFIT_TARGET_R="3.0"
  ENABLE_BREAKEVEN_STOP="true"
  BREAKEVEN_TRIGGER_PCT="0.005"
  BREAKEVEN_TRAIL_PCT="0.002"
  RELATIVE_VOLUME_THRESHOLD="2.0"
else
  ENABLE_LIVE_TRADING="true"
  PAPER_PROOF_FREEZE="false"
  RISK_PER_TRADE_PCT="0.0025"
  MAX_LOSS_PER_TRADE_DOLLARS=""
  MAX_OPEN_POSITIONS="3"
  MAX_PORTFOLIO_EXPOSURE_PCT="0.30"
  REPLAY_SLIPPAGE_BPS="5.0"
  ENABLE_VIX_FILTER="false"
  ENABLE_SECTOR_FILTER="false"
  ENABLE_VWAP_ENTRY_FILTER="false"
  ENABLE_PROFIT_TRAIL="false"
  ENABLE_PROFIT_TARGET="false"
  PROFIT_TARGET_R="2.0"
  ENABLE_BREAKEVEN_STOP="true"
  BREAKEVEN_TRIGGER_PCT="0.0025"
  BREAKEVEN_TRAIL_PCT="0.002"
  RELATIVE_VOLUME_THRESHOLD="1.5"
fi

cat >"$ENV_FILE" <<EOF
TRADING_MODE=$MODE
ENABLE_LIVE_TRADING=$ENABLE_LIVE_TRADING
STRATEGY_VERSION=v1-breakout

POSTGRES_DB=alpaca_bot
POSTGRES_USER=alpaca_bot
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
DATABASE_URL=postgresql://alpaca_bot:$POSTGRES_PASSWORD@postgres:5432/alpaca_bot
MARKET_DATA_FEED=iex
SYMBOLS=AAPL,MSFT,AMZN,NVDA,META,SPY,QQQ,IWM

DAILY_SMA_PERIOD=20
BREAKOUT_LOOKBACK_BARS=20
RELATIVE_VOLUME_LOOKBACK_BARS=20
RELATIVE_VOLUME_THRESHOLD=$RELATIVE_VOLUME_THRESHOLD
BULL_FLAG_MIN_RUN_PCT=0.02
BULL_FLAG_CONSOLIDATION_VOLUME_RATIO=0.6
BULL_FLAG_CONSOLIDATION_RANGE_PCT=0.5
ENTRY_TIMEFRAME_MINUTES=15

RISK_PER_TRADE_PCT=$RISK_PER_TRADE_PCT
MAX_POSITION_PCT=0.05
MAX_LOSS_PER_TRADE_DOLLARS=$MAX_LOSS_PER_TRADE_DOLLARS
MAX_OPEN_POSITIONS=$MAX_OPEN_POSITIONS
MAX_PORTFOLIO_EXPOSURE_PCT=$MAX_PORTFOLIO_EXPOSURE_PCT
DAILY_LOSS_LIMIT_PCT=0.01
INTRADAY_CONSECUTIVE_LOSS_GATE=0
REPLAY_SLIPPAGE_BPS=$REPLAY_SLIPPAGE_BPS
NIGHTLY_MAX_COMBOS=24
PAPER_PROOF_FREEZE=$PAPER_PROOF_FREEZE
PAPER_READINESS_MAX_PASS_AGE_MINUTES=180
PROFIT_PROBE_START_DATE=2026-06-30
PROFIT_PROBE_STRATEGY=bull_flag
PROFIT_PROBE_MIN_TRADES=10
PROFIT_PROBE_MIN_PNL=0.01
CONFIDENCE_FLOOR=0.25
ENABLE_VIX_FILTER=$ENABLE_VIX_FILTER
ENABLE_SECTOR_FILTER=$ENABLE_SECTOR_FILTER
ENABLE_VWAP_ENTRY_FILTER=$ENABLE_VWAP_ENTRY_FILTER
ENABLE_PROFIT_TRAIL=$ENABLE_PROFIT_TRAIL
PROFIT_TRAIL_PCT=0.90
ENABLE_PROFIT_TARGET=$ENABLE_PROFIT_TARGET
PROFIT_TARGET_R=$PROFIT_TARGET_R
ENABLE_BREAKEVEN_STOP=$ENABLE_BREAKEVEN_STOP
BREAKEVEN_TRIGGER_PCT=$BREAKEVEN_TRIGGER_PCT
BREAKEVEN_TRAIL_PCT=$BREAKEVEN_TRAIL_PCT
ENABLE_REGIME_FILTER=false
ENABLE_NEWS_FILTER=false
ENABLE_SPREAD_FILTER=false
ENABLE_OPTIONS_TRADING=false
OPTION_CHAIN_SYMBOLS=
STOP_LIMIT_BUFFER_PCT=0.0005
BREAKOUT_STOP_BUFFER_PCT=0.001
ENTRY_STOP_PRICE_BUFFER=0.02
ATR_PERIOD=20
ATR_STOP_MULTIPLIER=1.0
TRAILING_STOP_ATR_MULTIPLIER=1.0
TRAILING_STOP_PROFIT_TRIGGER_R=1.0

ENTRY_WINDOW_START=10:00
ENTRY_WINDOW_END=15:30
FLATTEN_TIME=15:45

ALPACA_PAPER_API_KEY=replace_me
ALPACA_PAPER_SECRET_KEY=replace_me
ALPACA_LIVE_API_KEY=replace_me
ALPACA_LIVE_SECRET_KEY=replace_me

DASHBOARD_AUTH_ENABLED=true
DASHBOARD_AUTH_USERNAME=$OPERATOR_USERNAME
DASHBOARD_AUTH_PASSWORD_HASH='replace_me'
EOF

chmod 600 "$ENV_FILE"
echo "created $ENV_FILE"
echo "fill in the Alpaca keys before starting the supervisor"
echo "set DASHBOARD_AUTH_PASSWORD_HASH before exposing the dashboard"
