#!/usr/bin/env bash
set -euo pipefail

ENV_FILE="${1:-/etc/alpaca_bot/alpaca-bot.env}"
MODE="${2:-paper}"
OPERATOR_USERNAME="${3:-operator@example.com}"

if [[ "$MODE" != "paper" && "$MODE" != "live" ]]; then
  echo "usage: $0 [env-file] [paper|live] [dashboard-username]" >&2
  exit 1
fi

mkdir -p "$(dirname "$ENV_FILE")"
mkdir -p /var/lib/alpaca-bot/nightly

if [[ -f "$ENV_FILE" ]]; then
  echo "env file already exists: $ENV_FILE" >&2
  exit 1
fi

POSTGRES_PASSWORD="$(python3 - <<'PY'
import secrets
print(secrets.token_urlsafe(24))
PY
)"

if [[ "$MODE" == "paper" ]]; then
  ENABLE_LIVE_TRADING="false"
  PAPER_PROOF_FREEZE="true"
  RISK_PER_TRADE_PCT="0.01"
  MAX_LOSS_PER_TRADE_DOLLARS="20.0"
  MAX_OPEN_POSITIONS="1"
  MAX_PORTFOLIO_EXPOSURE_PCT="0.30"
  REPLAY_SLIPPAGE_BPS="2.0"
  ENABLE_VIX_FILTER="false"
  ENABLE_SECTOR_FILTER="false"
  ENABLE_VWAP_ENTRY_FILTER="false"
  ENABLE_PROFIT_TRAIL="true"
  ENABLE_PROFIT_TARGET="true"
  PROFIT_TARGET_R="3.0"
  ENABLE_BREAKEVEN_STOP="true"
  BREAKEVEN_TRIGGER_PCT="0.005"
  BREAKEVEN_TRAIL_PCT="0.002"
  ENABLE_TREND_FILTER_EXIT="false"
  ENABLE_VWAP_BREAKDOWN_EXIT="false"
  ENABLE_NO_FOLLOW_THROUGH_EXIT="false"
  ENABLE_GIVEBACK_EXIT="true"
  ENABLE_EARLY_LOSS_EXIT="false"
  RELATIVE_VOLUME_THRESHOLD="2.0"
else
  ENABLE_LIVE_TRADING="true"
  PAPER_PROOF_FREEZE="false"
  RISK_PER_TRADE_PCT="0.0025"
  MAX_LOSS_PER_TRADE_DOLLARS=""
  MAX_OPEN_POSITIONS="3"
  MAX_PORTFOLIO_EXPOSURE_PCT="0.30"
  REPLAY_SLIPPAGE_BPS="5.0"
  ENABLE_VIX_FILTER="false"
  ENABLE_SECTOR_FILTER="false"
  ENABLE_VWAP_ENTRY_FILTER="false"
  ENABLE_PROFIT_TRAIL="false"
  ENABLE_PROFIT_TARGET="false"
  PROFIT_TARGET_R="2.0"
  ENABLE_BREAKEVEN_STOP="true"
  BREAKEVEN_TRIGGER_PCT="0.0025"
  BREAKEVEN_TRAIL_PCT="0.002"
  ENABLE_TREND_FILTER_EXIT="false"
  ENABLE_VWAP_BREAKDOWN_EXIT="false"
  ENABLE_NO_FOLLOW_THROUGH_EXIT="false"
  ENABLE_GIVEBACK_EXIT="false"
  ENABLE_EARLY_LOSS_EXIT="false"
  RELATIVE_VOLUME_THRESHOLD="1.5"
fi

cat >"$ENV_FILE" <<EOF
TRADING_MODE=$MODE
ENABLE_LIVE_TRADING=$ENABLE_LIVE_TRADING
STRATEGY_VERSION=v1-breakout

POSTGRES_DB=alpaca_bot
POSTGRES_USER=alpaca_bot
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
DATABASE_URL=postgresql://alpaca_bot:$POSTGRES_PASSWORD@postgres:5432/alpaca_bot
MARKET_DATA_FEED=iex
SYMBOLS=AAPL,MSFT,AMZN,NVDA,META,SPY,QQQ,IWM

DAILY_SMA_PERIOD=20
BREAKOUT_LOOKBACK_BARS=20
RELATIVE_VOLUME_LOOKBACK_BARS=10
RELATIVE_VOLUME_THRESHOLD=$RELATIVE_VOLUME_THRESHOLD
BULL_FLAG_MIN_RUN_PCT=0.02
BULL_FLAG_CONSOLIDATION_VOLUME_RATIO=0.6
BULL_FLAG_CONSOLIDATION_RANGE_PCT=0.5
ENTRY_TIMEFRAME_MINUTES=15
ENTRY_ORDER_ACTIVE_BARS=1

RISK_PER_TRADE_PCT=$RISK_PER_TRADE_PCT
MAX_POSITION_PCT=0.05
MAX_LOSS_PER_TRADE_DOLLARS=$MAX_LOSS_PER_TRADE_DOLLARS
MAX_OPEN_POSITIONS=$MAX_OPEN_POSITIONS
MAX_PORTFOLIO_EXPOSURE_PCT=$MAX_PORTFOLIO_EXPOSURE_PCT
DAILY_LOSS_LIMIT_PCT=0.01
INTRADAY_CONSECUTIVE_LOSS_GATE=0
REPLAY_SLIPPAGE_BPS=$REPLAY_SLIPPAGE_BPS
NIGHTLY_MAX_COMBOS=24
NIGHTLY_TIMEOUT_SECONDS=18000
SECOND_STRATEGY_SCAN_TIMEOUT_SECONDS=10800
SECOND_STRATEGY_OUTPUT_ROOT=/var/lib/alpaca-bot/nightly/second_strategy
SECOND_STRATEGY_EXCLUDE_CANDIDATES=vwap_cross
SECOND_STRATEGY_CANDIDATE_SCALES=0.10,0.25,0.50
SECOND_STRATEGY_INCLUDE_OPTION_CANDIDATES=auto
SECOND_STRATEGY_VALIDATE_POSITIVES=true
SECOND_STRATEGY_VALIDATE_ALL_POSITIVE_ROWS=true
SECOND_STRATEGY_MAX_VALIDATION_CANDIDATES=0
SECOND_STRATEGY_SCAN_JOBS=2
SECOND_STRATEGY_VALIDATION_SAMPLE_SIZE=160
SECOND_STRATEGY_VALIDATION_SAMPLE_SEED=second-strategy-independent-validation
PAPER_PROOF_FREEZE=$PAPER_PROOF_FREEZE
PAPER_READINESS_MAX_PASS_AGE_MINUTES=180
PROFIT_PROBE_START_DATE=2026-07-07
PROFIT_PROBE_STRATEGY=bull_flag
PROFIT_PROBE_STRATEGIES=bull_flag
PROFIT_PROBE_MIN_TRADES=30
PROFIT_PROBE_MIN_PNL=0.01
SESSION_GUARD_MIN_TRADES=10
SESSION_GUARD_FAIL_BELOW_PNL=0
PAPER_SCALE_MIN_TRADES=30
PAPER_SCALE_MIN_STRATEGIES=2
PAPER_APPROVED_STRATEGIES=bull_flag
PAPER_READINESS_DECISION_DRY_RUN_STRATEGIES=bull_flag
PAPER_ACTIVITY_STRATEGIES=bull_flag
SESSION_GUARD_STRATEGIES=bull_flag
PAPER_SCALE_MIN_ACTIVE_DAYS=5
PAPER_SCALE_MAX_SINGLE_WIN_PNL_SHARE=0.50
PAPER_SCALE_MIN_PROFIT_FACTOR=1.20
PAPER_SCALE_MAX_EOD_LOSS_SHARE=0.50
PAPER_SCALE_MAX_OPERATIONAL_EXIT_LOSS_SHARE=0.00
PAPER_EXECUTION_MIN_ENTRY_FILL_RATE=0.25
PAPER_EXECUTION_MAX_CAPACITY_REJECT_RATE=0.05
CONFIDENCE_FLOOR=0.25
ENABLE_VIX_FILTER=$ENABLE_VIX_FILTER
ENABLE_SECTOR_FILTER=$ENABLE_SECTOR_FILTER
ENABLE_VWAP_ENTRY_FILTER=$ENABLE_VWAP_ENTRY_FILTER
ENABLE_PROFIT_TRAIL=$ENABLE_PROFIT_TRAIL
PROFIT_TRAIL_PCT=0.90
ENABLE_PROFIT_TARGET=$ENABLE_PROFIT_TARGET
PROFIT_TARGET_R=$PROFIT_TARGET_R
ENABLE_BREAKEVEN_STOP=$ENABLE_BREAKEVEN_STOP
BREAKEVEN_TRIGGER_PCT=$BREAKEVEN_TRIGGER_PCT
BREAKEVEN_TRAIL_PCT=$BREAKEVEN_TRAIL_PCT
ENABLE_TREND_FILTER_EXIT=$ENABLE_TREND_FILTER_EXIT
ENABLE_VWAP_BREAKDOWN_EXIT=$ENABLE_VWAP_BREAKDOWN_EXIT
VWAP_BREAKDOWN_MIN_BARS=1
ENABLE_NO_FOLLOW_THROUGH_EXIT=$ENABLE_NO_FOLLOW_THROUGH_EXIT
NO_FOLLOW_THROUGH_EXIT_MINUTES=0
NO_FOLLOW_THROUGH_MIN_FAVORABLE_PCT=0.0025
ENABLE_GIVEBACK_EXIT=$ENABLE_GIVEBACK_EXIT
GIVEBACK_EXIT_MIN_FAVORABLE_PCT=0.0025
GIVEBACK_EXIT_MAX_RETURN_PCT=0.0
ENABLE_EARLY_LOSS_EXIT=$ENABLE_EARLY_LOSS_EXIT
EARLY_LOSS_EXIT_MINUTES=0
EARLY_LOSS_EXIT_RETURN_PCT=0.01
ENABLE_REGIME_FILTER=false
ENABLE_NEWS_FILTER=false
ENABLE_SPREAD_FILTER=false
ENABLE_OPTIONS_TRADING=false
OPTION_CHAIN_SYMBOLS=
STOP_LIMIT_BUFFER_PCT=0.0005
BREAKOUT_STOP_BUFFER_PCT=0.001
ENTRY_STOP_PRICE_BUFFER=0.02
ENTRY_MIN_CLOSE_TO_ENTRY_PCT=-0.01
ENTRY_MAX_CLOSE_TO_ENTRY_PCT=1.0
ATR_PERIOD=20
ATR_STOP_MULTIPLIER=1.0
TRAILING_STOP_ATR_MULTIPLIER=1.0
TRAILING_STOP_PROFIT_TRIGGER_R=1.0

ENTRY_WINDOW_START=10:00
ENTRY_WINDOW_END=15:30
FLATTEN_TIME=15:45

ALPACA_PAPER_API_KEY=replace_me
ALPACA_PAPER_SECRET_KEY=replace_me
ALPACA_LIVE_API_KEY=replace_me
ALPACA_LIVE_SECRET_KEY=replace_me

DASHBOARD_AUTH_ENABLED=true
DASHBOARD_AUTH_USERNAME=$OPERATOR_USERNAME
DASHBOARD_AUTH_PASSWORD_HASH='replace_me'
EOF

chmod 600 "$ENV_FILE"
echo "created $ENV_FILE"
echo "fill in the Alpaca keys before starting the supervisor"
echo "set DASHBOARD_AUTH_PASSWORD_HASH before exposing the dashboard"
